### ISSUE TITLE
Publish to PyPI?

### ISSUE THREAD

**Issue by maresb** [pymc-devs/pymc-sphinx-theme#2]
For PyMC, this theme is being installed via a git+https link in `conda-envs/environment-dev.yml`. For technical reasons it'd be way nicer if this were a package available on PyPI. Would it be possible to create a release?

**Comment by OriolAbril** [comment]
Yeah, I can copy the action from https://github.com/arviz-devs/xarray-einstats/blob/main/.github/workflows/publish.yml. Would that be ok? If you'd prefer a diferent workflow also feel free to send a PR with a different action

**Comment by maresb** [comment]
There's already an almost-identical action here. I think you just need to push a tag or something. I'm indifferent to the workflow.

Thanks!!!

**Comment by OriolAbril** [comment]
Done: https://pypi.org/project/pymc-sphinx-theme/ (might be a good idea to close once we have updated the requirements in the 3 repos to use pypi version instead of github)

**Comment by OriolAbril** [comment]
landing page+blog update the dependency with https://github.com/pymc-devs/pymc.io/pull/83

**Comment by OriolAbril** [comment]
for pymc: https://github.com/pymc-devs/pymc/pull/6628
